displayName: Provider Plugin Demo
type: provider
iconPath: .assets/icon.png

import: github.com/KCL-Electronics/traefik-cdn-whitelist

summary: '[Demo] Simple Provider Plugin'

testData:
  pollInterval: 5s
